version: '3.9'
services:
  backend:
    image: rajanguf/guestregistration-be:1.0
    container_name: guestregistration-be
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: password
      MYSQL_INITDB: always
      WAIT_HOSTS: mysql:3306
      WAIT_SLEEP_INTERVAL: 5
    networks:
      - app-network
    command: sh -c "/wait && java -jar app.jar"

  frontend:
    image: rajanguf/guestregistration-fe:1.0
    container_name: guestregistration-fe
    restart: always
    environment:
      REACT_APP_API_PORT: 8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.1.0
    container_name: guestregistration-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: guestregistrationDB
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
