
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate-dialect: org.hibernate.dialect.H2Dialect
      hibernate-format: 'true'
    hibernate:
      ddl-auto: none
springdoc:
  swagger-ui:
    operationsSorter: 'method'
  api-docs:
    path: '/api-docs'