spring:
  datasource:
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/guestregistrationDB?createDatabaseIfNotExist=true
    password: ${MYSQL_PASSWORD:password}
    initialization-mode: always
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: ${MYSQL_INITDB:never}
springdoc:
  swagger-ui:
    operationsSorter: 'method'
  api-docs:
    path: '/api-docs'